name: Crates CD

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'publish ')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish to crates.io
        run: cargo publish
