[package]
name = "neocurl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
mlua = { version = "0.10.3", features = ["lua54"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
