name: CI/CD
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --verbose
      - name: Run test
        run: cargo test --verbose

  test-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build CLI
        run: cargo build --release
      - name: Run CLI on test file
        run: ./target/release/ncurl test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format
        run: cargo fmt -- --check

  publish:
    runs-on: ubuntu-latest
    needs: [test, test-cli]
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'publish ')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Login into crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Build binaries in "release" mode
        run: cargo build -r
      - name: "Package for crates.io"
        run: cargo package
      - name: "Publish to crates.io"
        run: cargo publish
