name: CI/CD
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --verbose
      - name: Run test
        run: cargo test --verbose

  test-cli:
    runs-on: ubuntu-latest
    needs: [test, lint, format]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Create and install Python venv with orjson
        run: |
          python3.11 -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install orjson
      - name: Build CLI
        run: cargo build --release
      - name: Run CLI inside Python venv
        run: |
          source ./venv/bin/activate
          ./target/release/ncurl run post

  publish:
    runs-on: ubuntu-latest
    needs: [test-cli]
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'publish ')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Login into crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Build binaries in "release" mode
        run: cargo build -r
      - name: "Package for crates.io"
        run: cargo package
      - name: "Publish to crates.io"
        run: cargo publish
